name: Workflow with Secret

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret Variable
        run: echo "My secret token is ${{ secrets.MY_SECRET_TOKEN }}"
