name: Global Variables Example
on:
  push:
    branches:
      - main
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Global Variable
        run: |
          echo "MY_GLOBAL_VARIABLE=Hello, World!" >> $GITHUB_ENV
        env:
          MY_GLOBAL_VARIABLE: "Hello, World!"
      - name: Use Global Variable in Step 1
        run: |
          echo "Step 1: ${{ env.MY_GLOBAL_VARIABLE }}"
      - name: Use Global Variable in Step 2
        run: |
          echo "Step 2: ${{ env.MY_GLOBAL_VARIABLE }}"
          

