name: Workflow Run 2
on:
  push:
    branches:
      - main
jobs:
  workflow-run-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout
      - name: Run the Previous Workflow
        uses: ./.github/workflows/4_global_variable.yaml
      - name: After running the First Workflow
        run: echo "End of Original Workflow"
        