name: Custom Python Action Workflow 2
on:
  push:
    branches:
      - main
jobs:
  run_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout # Removed the version Number :: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Run Custom Action
        run: RameshGithubActions/Act1_CustomActionUsingPython

        