name: Workflow Task

on:
  push:
    branches:
      - main

jobs:
  Nested_If_Else:
    runs-on: ubuntu-latest
    steps:
      - name: Check conditions
        run: |
          if [ ${{ github.event_name }} == 'push' ]; then
            if [ ${{ github.event.head_commit.message }} == 'deploy' ]; then
              echo "Deploying the application..."
            else
              echo "Not deploying. Commit message does not contain 'deploy'."
            fi
          else
            echo "Not a push event."
          fi

  Secret_Variables:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret Variable
        run: echo "My secret token is ${{ secrets.MY_SECRET_TOKEN }}"

  Local_Variables:
    runs-on: ubuntu-latest
    env:
      ENV_STRING: "Hello, Ramesh!"
      ENV_INTEGER: 1234
    steps:
      - name: Set Local Variable
        run: |
          NORMAL_STRING="Hello, World!"
          NORMAL_INTEGER=5678

          echo "Normal local string: $NORMAL_STRING"
          echo "Normal local integer: $NORMAL_INTEGER"
          
          echo "Using Environment - local string: ${{ env.ENV_STRING }}"
          echo "Using Environment - local integer: ${{ env.ENV_INTEGER }}"

  Global_Variables:
    runs-on: ubuntu-latest
    steps:
      - name: Set Global Variable
        run: |
          echo "MY_GLOBAL_VARIABLE=Hello, Ramesh!" >> $GITHUB_ENV
      - name: Use Global Variable
        run: |
          echo "Step 1: ${{ env.MY_GLOBAL_VARIABLE }}"

  # Nested_Generic_Workflow:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Run the Previous Workflow
  #       uses: ./.github/workflows/sample_workflow.yaml
  #       with:
  #         input_arg: "Hello World!"
  #     - name: After running the First Workflow
  #       run: echo "End of Original Workflow"

  Custom_Python_Action:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: RameshGithubActions/Act1_CustomActionUsingPython@v2
        # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"

  # Exception_Handling_Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.12

  #     - name: Initiate npm
  #       run: npm init -y

  #     - name: Write build in Package
  #       run: |
  #         python add_build.py
  #         npm install

  #     - name: Build project
  #       run: npm run build
        
  #     - name: Test project
  #       run: npm test

  # Exception_Handling_Deploy_Success:
  #   runs-on: ubuntu-latest
  #   needs: Exception_Handling_Build
  #   if: ${{ success() && github.ref == 'refs/heads/main' }}
  #   steps:
  #     - name: Deploy to production
  #       run: echo "Deploy to production"
  #     - name: Deploy to staging
  #       run: echo "Deploy to staging"

  # Exception_Handling_Deploy_Failier:
  #   runs-on: ubuntu-latest
  #   needs: Exception_Handling_Build
  #   if: ${{ failure() || github.ref!= 'refs/heads/main' }}
  #   steps:
  #     - name: Deploy to production (failure)
  #       run: echo "Deploy to production failed"
  #     - name: Deploy to staging (failure)
  #       run: echo "Deploy to staging failed"
